#!/bin/bash

path=$(readlink -f "$0")
week_dir=$(dirname "$(dirname "$path")")
root_dir=$(dirname "$(dirname "$week_dir")")

cardano_cli="docker run --rm -it \
  --entrypoint cardano-cli \
  -e CARDANO_NODE_SOCKET_PATH=/ipc/node.socket \
  -v opshin-pioneer-program_node-db:/data \
  -v opshin-pioneer-program_node-ipc:/ipc \
  -v $root_dir:/opshin-pioneer-program
  inputoutput/cardano-node"

assets_dir=/opshin-pioneer-program/src/week02/assets
keys_dir=/opshin-pioneer-program/keys
local_keys_dir=$root_dir/keys


key_name="$1"
collateral="$2"
tx_in="$3"

# generated by cardano-cli
pp_path="$assets_dir/gift/protocol-parameters.json"
body_path="$assets_dir/gift/collect-gift.txbody"
tx_path="$assets_dir/gift/collect-gift.tx"

# Query the protocol parameters \
$cardano_cli query protocol-parameters \
  --testnet-magic 2 \
  --out-file "$pp_path"

# Build the transaction
change_addr=$(cat "$local_keys_dir/$key_name.addr")
$cardano_cli transaction build \
  --babbage-era \
  --testnet-magic 2 \
  --tx-in "$tx_in" \
  --tx-in-script-file "$assets_dir/gift/script.plutus" \
  --tx-in-inline-datum-present \
  --tx-in-redeemer-file "$assets_dir/unit.json" \
  --tx-in-collateral "$collateral" \
  --change-address "$change_addr" \
  --protocol-params-file "$pp_path" \
  --out-file "$body_path"

# Sign the transaction
$cardano_cli transaction sign \
  --tx-body-file "$body_path" \
  --signing-key-file "$keys_dir/$key_name.skey" \
  --testnet-magic 2 \
  --out-file "$tx_path"

# Submit the transaction
$cardano_cli transaction submit \
  --testnet-magic 2 \
  --tx-file "$tx_path"

tid=$($cardano_cli transaction txid --tx-file "$tx_path")
echo "transaction id: $tid"
echo "Cardanoscan: https://preview.cardanoscan.io/transaction/$tid"
