#!/bin/bash

path=$(readlink -f "$0")
week_dir=$(dirname "$(dirname "$path")")
root_dir=$(dirname "$(dirname "$week_dir")")

cardano_cli="docker run --rm -it \
  --entrypoint cardano-cli \
  -e CARDANO_NODE_SOCKET_PATH=/ipc/node.socket \
  -v opshin-pioneer-program_node-db:/data \
  -v opshin-pioneer-program_node-ipc:/ipc \
  -v $root_dir:/opshin-pioneer-program
  inputoutput/cardano-node"

assets_dir=/opshin-pioneer-program/src/week02/assets
local_assets_dir=$week_dir/assets
keys_dir=/opshin-pioneer-program/keys
local_keys_dir=$root_dir/keys

key_name="$1"
tx_in="$2"

echo "$key_name"
echo "$tx_in"

# generated by cardano-cli
body_path="$assets_dir/gift/gift.txbody"
tx_path="$assets_dir/gift/gift.tx"

# Build gift address
# opshin generates this for us
#$cardano_cli address build \
#  --payment-script-file "$assets_dir/gift/script.plutus" \
#  --testnet-magic 2 \
#  --out-file "$assets_dir/gift/testnet.addr"

# Build the transaction
script_addr=$(cat "$local_assets_dir/gift/testnet.addr")
change_addr=$(cat "$local_keys_dir/$key_name.addr")
$cardano_cli transaction build \
  --babbage-era \
  --testnet-magic 2 \
  --tx-in "$tx_in" \
  --tx-out "$script_addr + 3000000 lovelace" \
  --tx-out-inline-datum-file "$assets_dir/unit.json" \
  --change-address "$change_addr" \
  --out-file "$body_path"

# Sign the transaction
$cardano_cli transaction sign \
  --tx-body-file "$body_path" \
  --signing-key-file "$keys_dir/$key_name.skey" \
  --testnet-magic 2 \
  --out-file "$tx_path"

# Submit the transaction
$cardano_cli transaction submit \
  --testnet-magic 2 \
  --tx-file "$tx_path"

tid=$($cardano_cli transaction txid --tx-file "$tx_path")
echo "transaction id: $tid"
echo "Cardanoscan: https://preprod.cexplorer.io/tx/$tid"
